"use client";

import { RootLayout, themes } from "@repo/ui";
import localFont from "next/font/local";

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };
import "./globals.css";
import { DialogContainer } from "./portal/dialog";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<RootLayout
					appName="admin"
					forceThemeName="dark"
					shouldShowQueryDevtools
					shouldUseBaseline
					themes={themes.mapView}
				>
					<DialogContainer />
					{children}
				</RootLayout>
			</body>
		</html>
	);
}
