export enum STORAGE_KEY {
	CONFIGS = "CONFIGS",
	FEATURES = "FEATURES",
	IS_PERMISSION_SET = "IS_PERMISSION_HAS_SET",
	LOCATION_PERMISSION = "LOCATION_PERMISSION",
	NOTIFICATION_PERMISSION = "NOTIFICATION_PERMISSION",
	THEME = "THEME",
}
